### ISSUE TITLE
Suggestion for an implementation

### ISSUE THREAD

**Issue by halo** [prawnpdf/prawn-component#2]
Hello 👋🏻

I've done some initial (but stable) work for a components-gem for prawn [over here](https://github.com/halo/prawn-component). I'm wondering whether my implementation would be a candidate for this gem?

I've actively been working with prawn for 10 years and never quite managed to get the abstraction level right for reusable components. But I think I've landed now and was hoping for some feedback.

Thank you for your time.

**Comment by halo** [comment]
Is it that bad? 😄

(No seriously, is there anything I can help with to make the evaluation easier?)

**Comment by mogest** [comment]
Hi @halo, as it says on the README this project isn't maintained so I don't think you'll get any feedback sorry.  I'd go to the prawn community to see whether you can get a group of people keen to review and promote it.
